STJ-1: Project configuration #1
chuva-io/sisp_payments_js pull request #5
Opened 2021-09-07 16:37 UTC by FredSoares

2021-09-07 16:42 UTC, nnascim approved these changes

2021-09-07 16:44 UTC, nnascim requested changes
The PR description and commit message have the wrong prefix

2021-09-07 16:56 UTC, FabyoSK approved these changes

2021-09-07 17:05 UTC, luis737 approved these changes

2021-09-08 11:35 UTC, nnascim approved these changes

2021-09-08 11:35 UTC, merged